### ISSUE TITLE
The json data generated by converter different from REST API's paylaod

### ISSUE THREAD

**Issue by leonardhyu** [xenanetworks/open-automation-core#20]
@ArtemConstantinov I noticed that the json file generated by converter from .v2544 is different from the actual payload we pass via REST API. There is no `test_name` or `destination` fields in the json file but in the REST API payload.

Is this by design or a bug?

**Converted json:**

![Image](https://user-images.githubusercontent.com/17590289/207142615-af251da3-7464-440f-a606-0d6c5ae68389.png)

**REST API payload:**

![Image](https://user-images.githubusercontent.com/17590289/207142670-07373496-5699-4971-9fff-944e852d4d68.png)

**Comment by ArtemConstantinov** [comment]
The converter is not related to the api, it's only converting old config files to the new format which test suite from xoa-core expecting to get. 

Guys already need to adjust test-suites to an updated structure of the `port_identities` coz latest version of the core push updated version of that field which represents a list of dict instead dict of dict's
